<?php

/*
 * This file is part of the HTML sanitizer project.
 *
 * (c) Titouan Galopin <galopintitouan@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace HtmlSanitizer\Extension\MathMl;

use HtmlSanitizer\Extension\ExtensionInterface;

/**
 * @author Titouan Galopin <galopintitouan@gmail.com>
 *
 * @final
 */
class MathMlExtension implements ExtensionInterface
{
    public function getName(): string
    {
        return 'mathml';
    }

    public function createNodeVisitors(array $config = []): array
    {
        return [
            'math' => new NodeVisitor\mathNodeVisitor($config['tags']['math'] ?? []),
            'abs' => new NodeVisitor\absNodeVisitor($config['tags']['abs'] ?? []),
            'and' => new NodeVisitor\andNodeVisitor($config['tags']['and'] ?? []),
            'annotation' => new NodeVisitor\annotationNodeVisitor($config['tags']['annotation'] ?? []),
            'annotation-xml' => new NodeVisitor\annotationxmlNodeVisitor($config['tags']['annotation-xml'] ?? []),
            'apply' => new NodeVisitor\applyNodeVisitor($config['tags']['apply'] ?? []),
            'approx' => new NodeVisitor\approxNodeVisitor($config['tags']['approx'] ?? []),
            'arccos' => new NodeVisitor\arccosNodeVisitor($config['tags']['arccos'] ?? []),
            'arccosh' => new NodeVisitor\arccoshNodeVisitor($config['tags']['arccosh'] ?? []),
            'arccot' => new NodeVisitor\arccotNodeVisitor($config['tags']['arccot'] ?? []),
            'arccoth' => new NodeVisitor\arccothNodeVisitor($config['tags']['arccoth'] ?? []),
            'arccsc' => new NodeVisitor\arccscNodeVisitor($config['tags']['arccsc'] ?? []),
            'arccsch' => new NodeVisitor\arccschNodeVisitor($config['tags']['arccsch'] ?? []),
            'arcsec' => new NodeVisitor\arcsecNodeVisitor($config['tags']['arcsec'] ?? []),
            'arcsech' => new NodeVisitor\arcsechNodeVisitor($config['tags']['arcsech'] ?? []),
            'arcsin' => new NodeVisitor\arcsinNodeVisitor($config['tags']['arcsin'] ?? []),
            'arcsinh' => new NodeVisitor\arcsinhNodeVisitor($config['tags']['arcsinh'] ?? []),
            'arctan' => new NodeVisitor\arctanNodeVisitor($config['tags']['arctan'] ?? []),
            'arctanh' => new NodeVisitor\arctanhNodeVisitor($config['tags']['arctanh'] ?? []),
            'arg' => new NodeVisitor\argNodeVisitor($config['tags']['arg'] ?? []),
            'bind' => new NodeVisitor\bindNodeVisitor($config['tags']['bind'] ?? []),
            'bvar' => new NodeVisitor\bvarNodeVisitor($config['tags']['bvar'] ?? []),
            'card' => new NodeVisitor\cardNodeVisitor($config['tags']['card'] ?? []),
            'cartesianproduct' => new NodeVisitor\cartesianproductNodeVisitor($config['tags']['cartesianproduct'] ?? []),
            'cbytes' => new NodeVisitor\cbytesNodeVisitor($config['tags']['cbytes'] ?? []),
            'ceiling' => new NodeVisitor\ceilingNodeVisitor($config['tags']['ceiling'] ?? []),
            'cerror' => new NodeVisitor\cerrorNodeVisitor($config['tags']['cerror'] ?? []),
            'ci' => new NodeVisitor\ciNodeVisitor($config['tags']['ci'] ?? []),
            'cn' => new NodeVisitor\cnNodeVisitor($config['tags']['cn'] ?? []),
            'codomain' => new NodeVisitor\codomainNodeVisitor($config['tags']['codomain'] ?? []),
            'complexes' => new NodeVisitor\complexesNodeVisitor($config['tags']['complexes'] ?? []),
            'compose' => new NodeVisitor\composeNodeVisitor($config['tags']['compose'] ?? []),
            'condition' => new NodeVisitor\conditionNodeVisitor($config['tags']['condition'] ?? []),
            'conjugate' => new NodeVisitor\conjugateNodeVisitor($config['tags']['conjugate'] ?? []),
            'cos' => new NodeVisitor\cosNodeVisitor($config['tags']['cos'] ?? []),
            'cosh' => new NodeVisitor\coshNodeVisitor($config['tags']['cosh'] ?? []),
            'cot' => new NodeVisitor\cotNodeVisitor($config['tags']['cot'] ?? []),
            'coth' => new NodeVisitor\cothNodeVisitor($config['tags']['coth'] ?? []),
            'cs' => new NodeVisitor\csNodeVisitor($config['tags']['cs'] ?? []),
            'csc' => new NodeVisitor\cscNodeVisitor($config['tags']['csc'] ?? []),
            'csch' => new NodeVisitor\cschNodeVisitor($config['tags']['csch'] ?? []),
            'csymbol' => new NodeVisitor\csymbolNodeVisitor($config['tags']['csymbol'] ?? []),
            'curl' => new NodeVisitor\curlNodeVisitor($config['tags']['curl'] ?? []),
            'declare' => new NodeVisitor\declareNodeVisitor($config['tags']['declare'] ?? []),
            'degree' => new NodeVisitor\degreeNodeVisitor($config['tags']['degree'] ?? []),
            'determinant' => new NodeVisitor\determinantNodeVisitor($config['tags']['determinant'] ?? []),
            'diff' => new NodeVisitor\diffNodeVisitor($config['tags']['diff'] ?? []),
            'divergence' => new NodeVisitor\divergenceNodeVisitor($config['tags']['divergence'] ?? []),
            'divide' => new NodeVisitor\divideNodeVisitor($config['tags']['divide'] ?? []),
            'domain' => new NodeVisitor\domainNodeVisitor($config['tags']['domain'] ?? []),
            'domainofapplication' => new NodeVisitor\domainofapplicationNodeVisitor($config['tags']['domainofapplication'] ?? []),
            'emptyset' => new NodeVisitor\emptysetNodeVisitor($config['tags']['emptyset'] ?? []),
            'eq' => new NodeVisitor\eqNodeVisitor($config['tags']['eq'] ?? []),
            'equivalent' => new NodeVisitor\equivalentNodeVisitor($config['tags']['equivalent'] ?? []),
            'eulergamma' => new NodeVisitor\eulergammaNodeVisitor($config['tags']['eulergamma'] ?? []),
            'exists' => new NodeVisitor\existsNodeVisitor($config['tags']['exists'] ?? []),
            'exp' => new NodeVisitor\expNodeVisitor($config['tags']['exp'] ?? []),
            'exponentiale' => new NodeVisitor\exponentialeNodeVisitor($config['tags']['exponentiale'] ?? []),
            'factorial' => new NodeVisitor\factorialNodeVisitor($config['tags']['factorial'] ?? []),
            'factorof' => new NodeVisitor\factorofNodeVisitor($config['tags']['factorof'] ?? []),
            'false' => new NodeVisitor\falseNodeVisitor($config['tags']['false'] ?? []),
            'floor' => new NodeVisitor\floorNodeVisitor($config['tags']['floor'] ?? []),
            'fn' => new NodeVisitor\fnNodeVisitor($config['tags']['fn'] ?? []),
            'forall' => new NodeVisitor\forallNodeVisitor($config['tags']['forall'] ?? []),
            'gcd' => new NodeVisitor\gcdNodeVisitor($config['tags']['gcd'] ?? []),
            'geq' => new NodeVisitor\geqNodeVisitor($config['tags']['geq'] ?? []),
            'grad' => new NodeVisitor\gradNodeVisitor($config['tags']['grad'] ?? []),
            'gt' => new NodeVisitor\gtNodeVisitor($config['tags']['gt'] ?? []),
            'ident' => new NodeVisitor\identNodeVisitor($config['tags']['ident'] ?? []),
            'image' => new NodeVisitor\imageNodeVisitor($config['tags']['image'] ?? []),
            'imaginary' => new NodeVisitor\imaginaryNodeVisitor($config['tags']['imaginary'] ?? []),
            'imaginaryi' => new NodeVisitor\imaginaryiNodeVisitor($config['tags']['imaginaryi'] ?? []),
            'implies' => new NodeVisitor\impliesNodeVisitor($config['tags']['implies'] ?? []),
            'in' => new NodeVisitor\inNodeVisitor($config['tags']['in'] ?? []),
            'infinity' => new NodeVisitor\infinityNodeVisitor($config['tags']['infinity'] ?? []),
            'int' => new NodeVisitor\intNodeVisitor($config['tags']['int'] ?? []),
            'integers' => new NodeVisitor\integersNodeVisitor($config['tags']['integers'] ?? []),
            'intersect' => new NodeVisitor\intersectNodeVisitor($config['tags']['intersect'] ?? []),
            'interval' => new NodeVisitor\intervalNodeVisitor($config['tags']['interval'] ?? []),
            'inverse' => new NodeVisitor\inverseNodeVisitor($config['tags']['inverse'] ?? []),
            'lambda' => new NodeVisitor\lambdaNodeVisitor($config['tags']['lambda'] ?? []),
            'laplacian' => new NodeVisitor\laplacianNodeVisitor($config['tags']['laplacian'] ?? []),
            'lcm' => new NodeVisitor\lcmNodeVisitor($config['tags']['lcm'] ?? []),
            'leq' => new NodeVisitor\leqNodeVisitor($config['tags']['leq'] ?? []),
            'limit' => new NodeVisitor\limitNodeVisitor($config['tags']['limit'] ?? []),
            'list' => new NodeVisitor\listNodeVisitor($config['tags']['list'] ?? []),
            'ln' => new NodeVisitor\lnNodeVisitor($config['tags']['ln'] ?? []),
            'log' => new NodeVisitor\logNodeVisitor($config['tags']['log'] ?? []),
            'logbase' => new NodeVisitor\logbaseNodeVisitor($config['tags']['logbase'] ?? []),
            'lowlimit' => new NodeVisitor\lowlimitNodeVisitor($config['tags']['lowlimit'] ?? []),
            'lt' => new NodeVisitor\ltNodeVisitor($config['tags']['lt'] ?? []),
            'maction' => new NodeVisitor\mactionNodeVisitor($config['tags']['maction'] ?? []),
            'maligngroup' => new NodeVisitor\maligngroupNodeVisitor($config['tags']['maligngroup'] ?? []),
            'malignmark' => new NodeVisitor\malignmarkNodeVisitor($config['tags']['malignmark'] ?? []),
            'matrix' => new NodeVisitor\matrixNodeVisitor($config['tags']['matrix'] ?? []),
            'matrixrow' => new NodeVisitor\matrixrowNodeVisitor($config['tags']['matrixrow'] ?? []),
            'max' => new NodeVisitor\maxNodeVisitor($config['tags']['max'] ?? []),
            'mean' => new NodeVisitor\meanNodeVisitor($config['tags']['mean'] ?? []),
            'median' => new NodeVisitor\medianNodeVisitor($config['tags']['median'] ?? []),
            'menclose' => new NodeVisitor\mencloseNodeVisitor($config['tags']['menclose'] ?? []),
            'merror' => new NodeVisitor\merrorNodeVisitor($config['tags']['merror'] ?? []),
            'mfenced' => new NodeVisitor\mfencedNodeVisitor($config['tags']['mfenced'] ?? []),
            'mfrac' => new NodeVisitor\mfracNodeVisitor($config['tags']['mfrac'] ?? []),
            'mglyph' => new NodeVisitor\mglyphNodeVisitor($config['tags']['mglyph'] ?? []),
            'mi' => new NodeVisitor\miNodeVisitor($config['tags']['mi'] ?? []),
            'min' => new NodeVisitor\minNodeVisitor($config['tags']['min'] ?? []),
            'minus' => new NodeVisitor\minusNodeVisitor($config['tags']['minus'] ?? []),
            'mlabeledtr' => new NodeVisitor\mlabeledtrNodeVisitor($config['tags']['mlabeledtr'] ?? []),
            'mlongdiv' => new NodeVisitor\mlongdivNodeVisitor($config['tags']['mlongdiv'] ?? []),
            'mmultiscripts' => new NodeVisitor\mmultiscriptsNodeVisitor($config['tags']['mmultiscripts'] ?? []),
            'mn' => new NodeVisitor\mnNodeVisitor($config['tags']['mn'] ?? []),
            'mo' => new NodeVisitor\moNodeVisitor($config['tags']['mo'] ?? []),
            'mode' => new NodeVisitor\modeNodeVisitor($config['tags']['mode'] ?? []),
            'moment' => new NodeVisitor\momentNodeVisitor($config['tags']['moment'] ?? []),
            'momentabout' => new NodeVisitor\momentaboutNodeVisitor($config['tags']['momentabout'] ?? []),
            'mover' => new NodeVisitor\moverNodeVisitor($config['tags']['mover'] ?? []),
            'mpadded' => new NodeVisitor\mpaddedNodeVisitor($config['tags']['mpadded'] ?? []),
            'mphantom' => new NodeVisitor\mphantomNodeVisitor($config['tags']['mphantom'] ?? []),
            'mprescripts' => new NodeVisitor\mprescriptsNodeVisitor($config['tags']['mprescripts'] ?? []),
            'mroot' => new NodeVisitor\mrootNodeVisitor($config['tags']['mroot'] ?? []),
            'mrow' => new NodeVisitor\mrowNodeVisitor($config['tags']['mrow'] ?? []),
            'ms' => new NodeVisitor\msNodeVisitor($config['tags']['ms'] ?? []),
            'mscarries' => new NodeVisitor\mscarriesNodeVisitor($config['tags']['mscarries'] ?? []),
            'mscarry' => new NodeVisitor\mscarryNodeVisitor($config['tags']['mscarry'] ?? []),
            'msgroup' => new NodeVisitor\msgroupNodeVisitor($config['tags']['msgroup'] ?? []),
            'msline' => new NodeVisitor\mslineNodeVisitor($config['tags']['msline'] ?? []),
            'mspace' => new NodeVisitor\mspaceNodeVisitor($config['tags']['mspace'] ?? []),
            'msqrt' => new NodeVisitor\msqrtNodeVisitor($config['tags']['msqrt'] ?? []),
            'msrow' => new NodeVisitor\msrowNodeVisitor($config['tags']['msrow'] ?? []),
            'mstack' => new NodeVisitor\mstackNodeVisitor($config['tags']['mstack'] ?? []),
            'mstyle' => new NodeVisitor\mstyleNodeVisitor($config['tags']['mstyle'] ?? []),
            'msub' => new NodeVisitor\msubNodeVisitor($config['tags']['msub'] ?? []),
            'msubsup' => new NodeVisitor\msubsupNodeVisitor($config['tags']['msubsup'] ?? []),
            'msup' => new NodeVisitor\msupNodeVisitor($config['tags']['msup'] ?? []),
            'mtable' => new NodeVisitor\mtableNodeVisitor($config['tags']['mtable'] ?? []),
            'mtd' => new NodeVisitor\mtdNodeVisitor($config['tags']['mtd'] ?? []),
            'mtext' => new NodeVisitor\mtextNodeVisitor($config['tags']['mtext'] ?? []),
            'mtr' => new NodeVisitor\mtrNodeVisitor($config['tags']['mtr'] ?? []),
            'munder' => new NodeVisitor\munderNodeVisitor($config['tags']['munder'] ?? []),
            'munderover' => new NodeVisitor\munderoverNodeVisitor($config['tags']['munderover'] ?? []),
            'naturalnumbers' => new NodeVisitor\naturalnumbersNodeVisitor($config['tags']['naturalnumbers'] ?? []),
            'neq' => new NodeVisitor\neqNodeVisitor($config['tags']['neq'] ?? []),
            'none' => new NodeVisitor\noneNodeVisitor($config['tags']['none'] ?? []),
            'not' => new NodeVisitor\notNodeVisitor($config['tags']['not'] ?? []),
            'notanumber' => new NodeVisitor\notanumberNodeVisitor($config['tags']['notanumber'] ?? []),
            'notin' => new NodeVisitor\notinNodeVisitor($config['tags']['notin'] ?? []),
            'notprsubset' => new NodeVisitor\notprsubsetNodeVisitor($config['tags']['notprsubset'] ?? []),
            'notsubset' => new NodeVisitor\notsubsetNodeVisitor($config['tags']['notsubset'] ?? []),
            'or' => new NodeVisitor\orNodeVisitor($config['tags']['or'] ?? []),
            'otherwise' => new NodeVisitor\otherwiseNodeVisitor($config['tags']['otherwise'] ?? []),
            'outerproduct' => new NodeVisitor\outerproductNodeVisitor($config['tags']['outerproduct'] ?? []),
            'partialdiff' => new NodeVisitor\partialdiffNodeVisitor($config['tags']['partialdiff'] ?? []),
            'pi' => new NodeVisitor\piNodeVisitor($config['tags']['pi'] ?? []),
            'piece' => new NodeVisitor\pieceNodeVisitor($config['tags']['piece'] ?? []),
            'piecewise' => new NodeVisitor\piecewiseNodeVisitor($config['tags']['piecewise'] ?? []),
            'plus' => new NodeVisitor\plusNodeVisitor($config['tags']['plus'] ?? []),
            'power' => new NodeVisitor\powerNodeVisitor($config['tags']['power'] ?? []),
            'primes' => new NodeVisitor\primesNodeVisitor($config['tags']['primes'] ?? []),
            'product' => new NodeVisitor\productNodeVisitor($config['tags']['product'] ?? []),
            'prsubset' => new NodeVisitor\prsubsetNodeVisitor($config['tags']['prsubset'] ?? []),
            'quotient' => new NodeVisitor\quotientNodeVisitor($config['tags']['quotient'] ?? []),
            'rationals' => new NodeVisitor\rationalsNodeVisitor($config['tags']['rationals'] ?? []),
            'real' => new NodeVisitor\realNodeVisitor($config['tags']['real'] ?? []),
            'reals' => new NodeVisitor\realsNodeVisitor($config['tags']['reals'] ?? []),
            'reln' => new NodeVisitor\relnNodeVisitor($config['tags']['reln'] ?? []),
            'rem' => new NodeVisitor\remNodeVisitor($config['tags']['rem'] ?? []),
            'root' => new NodeVisitor\rootNodeVisitor($config['tags']['root'] ?? []),
            'scalarproduct' => new NodeVisitor\scalarproductNodeVisitor($config['tags']['scalarproduct'] ?? []),
            'sdev' => new NodeVisitor\sdevNodeVisitor($config['tags']['sdev'] ?? []),
            'sec' => new NodeVisitor\secNodeVisitor($config['tags']['sec'] ?? []),
            'sech' => new NodeVisitor\sechNodeVisitor($config['tags']['sech'] ?? []),
            'selector' => new NodeVisitor\selectorNodeVisitor($config['tags']['selector'] ?? []),
            'semantics' => new NodeVisitor\semanticsNodeVisitor($config['tags']['semantics'] ?? []),
            'sep' => new NodeVisitor\sepNodeVisitor($config['tags']['sep'] ?? []),
            'set' => new NodeVisitor\setNodeVisitor($config['tags']['set'] ?? []),
            'setdiff' => new NodeVisitor\setdiffNodeVisitor($config['tags']['setdiff'] ?? []),
            'share' => new NodeVisitor\shareNodeVisitor($config['tags']['share'] ?? []),
            'sin' => new NodeVisitor\sinNodeVisitor($config['tags']['sin'] ?? []),
            'sinh' => new NodeVisitor\sinhNodeVisitor($config['tags']['sinh'] ?? []),
            'subset' => new NodeVisitor\subsetNodeVisitor($config['tags']['subset'] ?? []),
            'sum' => new NodeVisitor\sumNodeVisitor($config['tags']['sum'] ?? []),
            'tan' => new NodeVisitor\tanNodeVisitor($config['tags']['tan'] ?? []),
            'tanh' => new NodeVisitor\tanhNodeVisitor($config['tags']['tanh'] ?? []),
            'tendsto' => new NodeVisitor\tendstoNodeVisitor($config['tags']['tendsto'] ?? []),
            'times' => new NodeVisitor\timesNodeVisitor($config['tags']['times'] ?? []),
            'transpose' => new NodeVisitor\transposeNodeVisitor($config['tags']['transpose'] ?? []),
            'true' => new NodeVisitor\trueNodeVisitor($config['tags']['true'] ?? []),
            'union' => new NodeVisitor\unionNodeVisitor($config['tags']['union'] ?? []),
            'uplimit' => new NodeVisitor\uplimitNodeVisitor($config['tags']['uplimit'] ?? []),
            'variance' => new NodeVisitor\varianceNodeVisitor($config['tags']['variance'] ?? []),
            'vector' => new NodeVisitor\vectorNodeVisitor($config['tags']['vector'] ?? []),
            'vectorproduct' => new NodeVisitor\vectorproductNodeVisitor($config['tags']['vectorproduct'] ?? []),
            'xor' => new NodeVisitor\xorNodeVisitor($config['tags']['xor'] ?? []),
        ];
    }
}
